Repository Simple-as-Coding/tutoring-platform, pull requests merged in 2023-07, with the labels that each got.

#96 task/95-Create contributors list
  CONTRIBUTORS.md
Labels: documentation, good first issue, task

#117 feature/add_scripts_to_start_mailserver
  README.md
  scripts/mailserver-launch-starter/mailserver-launch-starter.bash
  scripts/mailserver-launch-starter/mailserver-launch-starter.ps1
  src/main/resources/application.properties
Labels: scripts

#97 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: documentation

#123 test/Test for UserServiceImpl - getUserByUsername
  src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
Labels: Unit tests

#119 Fix/deleted "-T 1C" from readme.md
  README.md
Labels: documentation

#126 fixed building containers in powershell scripts
  scripts/database-launch-starter/database-launch-starter.ps1
  scripts/mailserver-launch-starter/mailserver-launch-starter.ps1
Labels: bug, scripts

#148 Update "Contributors.md" data xan
  CONTRIBUTORS.md
Labels: doc/

#147 Feature/GitHub action should not check when contributorsmd is changed + by the way
  .github/workflows/build.yml
Labels: feature/, GH Action

#152 Refactor test methods in UserServiceImplTest class to adhere to the given-when-then convention using BDDMockito syntax #151
  src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
Labels: refactor/, Unit Test

#154 [FIX] Fix typos in README.md
  README.md
Labels: bugfix/, doc/

#153 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: doc/

#149 Test for UserServiceImpl - checkUserExists #151
  src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
Labels: Unit Test

#128 Test for user service impl confirm user registration
  CONTRIBUTORS.md
  src/main/java/pl/simpleascoding/tutoringplatform/user/UserServiceImpl.java
  src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
  src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceMethodsForTests.java
Labels: Unit Test

#150 Test for UserServiceImpl - loadUserByUsername #106
  src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
Labels: Unit Test

#155 Test for TeacherServiceImpl - addTeacherRoleToUser
  src/test/java/pl/simpleascoding/tutoringplatform/user/TeacherServiceImplTest.java
Labels: Unit Test
